name: inlib_nav
description: "InLib Guide is an indoor navigation app designed for libraries, helping users quickly locate books. With an intuitive interface and real-time directions, it enhances the library experience by making exploration simple and efficient."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 0.0.1+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_camera: ^1.0.0
  image_picker: ^1.1.2
  vector_math: ^2.1.4
  ar_flutter_plugin_updated: ^0.0.1
  permission_handler: ^11.4.0
  camera: ^0.10.6
  audioplayers: ^6.4.0
  provider: ^6.1.4
  vibration: ^3.1.3
  flutter_tts: ^4.2.2
  google_mlkit_barcode_scanning: ^0.14.1
  google_mlkit_text_recognition: ^0.15.0
  google_mlkit_image_labeling: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/inlib_logo.png
    - assets/images/inlib_logo_trsp.png
    - assets/images/inlib_logo2_trsp.png
    - assets/images/correct_way.png
    - assets/images/wrong_way.png
    - assets/images/qrcodes/